### ISSUE TITLE
Add new resolver list. List of open resolvers no longer avalible.

### ISSUE THREAD

**Issue by 7etsuo** [snowcra5h/j0lt-ddos-tool#3]
https://github.com/snowcra5h/j0lt-ddos-tool/blob/b2db3781d7cc1e3bbb1df857a4d2b7bb408d4ed1/j0lt.c#L159

**Comment by deathpoint111** [comment]
> https://github.com/snowcra5h/j0lt-ddos-tool/blob/b2db3781d7cc1e3bbb1df857a4d2b7bb408d4ed1/j0lt.c#L159
it will available in your current program dir after downloaded

**Comment by 7etsuo** [comment]
> 
Oh wow, this was down for a while. I see it's back up. Thank you for pointing this out.
